### ISSUE TITLE
Why does the onex tool remove itself automatically?

### ISSUE THREAD

**Issue by STARGAMERMJ** [rajkumardusad/onex#102]
When I exit from my termux terminal, I scroll down the notification bar and click on the termux exit button. Then whenever I reopen the app, the Onex tool automatically disappears. I have other tools, but they never disappear.

**Comment by rajkumardusad** [comment]
Hey @STARGAMERMJ its never disappear, its always on your terminal just type onex in your terminal.

**Comment by STARGAMERMJ** [comment]
> Hey @STARGAMERMJ its never disappear, its always on your terminal just type onex in your terminal.

What is this bro 😅.

@KasRoudra
