### ISSUE TITLE
 Sorry : onex is not installed !!  Please try again

### ISSUE THREAD

**Issue by xeno21** [rajkumardusad/onex#11]

**Comment by rajkumardusad** [comment]
Hey @xeno21 what is the error?

**Comment by xeno21** [comment]
hey @rajkumardusad when i type:sh onex/install, appears Sorry : onex is not installed !! Please try again

**Comment by xeno21** [comment]
i'm using the kali linux terminal

**Comment by rajkumardusad** [comment]
Yes try with root access.
`$ sudo sh onex/install`
I hope it will works.

**Comment by xeno21** [comment]
i tried and the message is the same but now if i type "onex" appears:"type onex help for help

**Comment by xeno21** [comment]
ok it works, but now how can i run a tool after i installed it?

**Comment by rajkumardusad** [comment]
Which tool you want to run?

**Comment by xeno21** [comment]
fluxion

**Comment by rajkumardusad** [comment]
Use following commnads :
`$ cd fluxion`
`$ ./fluxion.sh`
I hope this will works for you?

**Comment by xeno21** [comment]
ok thanks bro for the help

**Comment by HariKrishna100** [comment]
sudo sh onex/install it didn't work for me in kali linux windows subsystem for linux
to install the tool

**Comment by rajkumardusad** [comment]
Hey @HariKrishna100 try without sudo, may be it works
