### ISSUE TITLE
Command to uninstall

### ISSUE THREAD

**Issue by togangel** [rajkumardusad/onex#14]
How to unistall onex?
Just is delete 
rm /data/data/com.termux/files/usr/bin/onex 
rm -rf /data/data/com.termux/files/usr/etc/onex
or is need other delete?

**Comment by rajkumardusad** [comment]
Hey @togangel you uninstall onex using following commands : 
`$ onex remove`
OR
`$ onex -r`
It will uninstall onex tool.

**Comment by togangel** [comment]
Muchas gracias!
Excelente Herramienta!!!!
