### ISSUE TITLE
onex was not installed!

### ISSUE THREAD

**Issue by battouusai** [rajkumardusad/onex#15]
i tried installing onex with "./onex/install" and all the other commands but still no work. i came to onex because of network connection issue in tool-x

**Comment by rajkumardusad** [comment]
Hey @battouusai what is error it will display?

**Comment by battouusai** [comment]
@rajkumardusad it shows "Sorry: onex is not installed!". I've used both "sh" and "./" commands even with sudo command but no work

**Comment by rajkumardusad** [comment]
Hey @battouusai which system you are using?

**Comment by battouusai** [comment]
@rajkumardusad kali linux on hp

**Comment by rajkumardusad** [comment]
Hey @battouusai delete the onex that you have installed and re-install with sudo, i hope it works

**Comment by AyushAJ15** [comment]
"No network connection"
Are you Offline?
Please try again after sometime.

I am facing these issue please help!!!
