### ISSUE TITLE
MacOS install: wget: No such file or directory error

### ISSUE THREAD

**Issue by ExeRhythm** [rajkumardusad/onex#18]
When trying to install onex on my Mac, it fails. Output:

  ___  _ __   _____  __
 / _ \| '_ \ / _ \ \/ /
| (_) | | | |  __/>  < 
 \___/|_| |_|\___/_/\_\

```
 Installing .... 
 Running setup .... 
install: wget: No such file or directory
mv: rename onex/onex to /usr/bin/onex: Read-only file system
chmod: /usr/bin/onex: No such file or directory
mv: rename onex to /etc/onex: Directory not empty
```

Any ideas how to fix this?

**Comment by ExeRhythm** [comment]
I tried. Doesn't work. I just instaled vm. Now everything runs smoothly
суббота, 22 августа 2020 г. пользователь Rajkumar Dusad <
notifications@github.com> написал:
> Hey @ExeRhythm sorry for the delay, try with sudo may be it works or we
will fix it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/0PdO-GRxhqA8YBotWP5rtRdJFBTWxPjxaeYU_pwbt61CaDBrL9w_aTIwq5CzJGmTQQSyRGgaLura-rWDws0PGH0VGbGjNyuZSAQMCd3SwOukBPdts1ojqR3ZHJq1Me-fXjHlQ1LoHZoHJeGOVRR2dVj9H5iplE7VCp7YasTE6sFoeZHbCxrPGDKWXu0HJ0z0iIUv8LGwCfBE8XaQfZ6Zmxed87G8UsyEf3S2bu1R4A=s0-d-e1-ft#https://github.com/notifications/beacon/AMQHNDRIRXTKLOPWLOQEJADSB7LFJA5CNFSM4QEZ65IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFBZWA7A.gif>

**Comment by rajkumardusad** [comment]
Hey @ExeRhythm what is vm?

**Comment by ExeRhythm** [comment]
Virtual Machine (e.g. VirtualBox, VMWare)

понедельник, 24 августа 2020 г. пользователь Rajkumar Dusad <
notifications@github.com> написал:
> Hey @ExeRhythm what is vm?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/z7RCFBLMuc9XZir9yICk0TyzeWvOStAMoT4BumCO2XKIo0qkrWJN-tdpi-aDZY36ndQhZD0y-sdg23PEA0nYEC4FJkYNaxgdiahtV3d5qrd8HEs9H3pG8t-T9SbaJ-_TppDdzAVAe0iPDJTKkTEC2_eZuUM6Ed5C4IVMuijgzC4OGNtFD4R8j0gSDOTfhqtOdZUvMDLidSXA6I_seqrn4ZSPfMnoPZjqyN9z8Up7RA=s0-d-e1-ft#https://github.com/notifications/beacon/AMQHNDWKHX3BRMJERZ6CNTTSCICTVA5CNFSM4QEZ65IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFB33EDI.gif>

**Comment by rajkumardusad** [comment]
> Virtual Machine (e.g. VirtualBox, VMWare) понедельник, 24 августа 2020 г. пользователь Rajkumar Dusad < notifications@github.com> написал:
> Hey @ExeRhythm what is vm? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.<
> https://ci3.googleusercontent.com/proxy/z7RCFBLMuc9XZir9yICk0TyzeWvOStAMoT4BumCO2XKIo0qkrWJN-tdpi-aDZY36ndQhZD0y-sdg23PEA0nYEC4FJkYNaxgdiahtV3d5qrd8HEs9H3pG8t-T9SbaJ-_TppDdzAVAe0iPDJTKkTEC2_eZuUM6Ed5C4IVMuijgzC4OGNtFD4R8j0gSDOTfhqtOdZUvMDLidSXA6I_seqrn4ZSPfMnoPZjqyN9z8Up7RA=s0-d-e1-ft#https://github.com/notifications/beacon/AMQHNDWKHX3BRMJERZ6CNTTSCICTVA5CNFSM4QEZ65IKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFB33EDI.gif>

That mean this tool not works in macOS?

**Comment by ExeRhythm** [comment]
Nope, doesn’t work

Отправлено с iPhone

**Comment by rajkumardusad** [comment]
Ok

**Comment by rajkumardusad** [comment]
Now its works in mac, i have tested it on macbook air.
