### ISSUE TITLE
How to use any tool like Empire

### ISSUE THREAD

**Issue by harshit954** [rajkumardusad/onex#22]

**Comment by root144** [comment]
onex -h : command not found

**Comment by rajkumardusad** [comment]
Hey @harshit954 type following command to run Empire tool : 
`$ cd Empire`
`$ ./setup/install.sh`
It will run the empire tool in your terminal.

**Comment by rajkumardusad** [comment]
> onex -h : command not found

Hey @root144 please install onex tool it will works.
