### ISSUE TITLE
how do we actually use the tools

### ISSUE THREAD

**Issue by Nuke-cpu** [rajkumardusad/onex#23]

**Comment by Nuke-cpu** [comment]
ok so after installing onex and then installing a tool, how the hell do you use the tool or run it?

**Comment by rajkumardusad** [comment]
Hey @Nuke-cpu type following command to run Empire tool : 
`$ cd Empire`
`$ ./setup/install.sh`
It will run the empire tool in your terminal. every tool have a different process to execute.

**Comment by Nuke-cpu** [comment]
> Hey @Nuke-cpu type following command to run Empire tool :
> `$ cd Empire`
> `$ ./setup/install.sh`
> It will run the empire tool in your terminal. every tool have a different process to execute.

thanks man

**Comment by Nuke-cpu** [comment]
> Hey @Nuke-cpu type following command to run Empire tool :
> `$ cd Empire`
> `$ ./setup/install.sh`
> It will run the empire tool in your terminal. every tool have a different process to execute.

i tried it and it doesnt work for some reason. im really confused man

**Comment by b4j1ng4n01** [comment]
Password apa

**Comment by b4j1ng4n01** [comment]
Kok passwordnya gk bisa

**Comment by b4j1ng4n01** [comment]
Kirimkan kodenya

**Comment by rajkumardusad** [comment]
Hey @b4j1ng4n01 can we talk in english?

**Comment by b4j1ng4n01** [comment]
Saya tidak bisa bahaha inggris
