### ISSUE TITLE
Format Error

### ISSUE THREAD

**Issue by mawoka-myblock** [rajkumardusad/onex#25]
Hello, I installed it and after "onex start" it gave me this ouput:
\033[01;33m
  ___  _ __   ___\033[01;31m__  __
\033[01;33m / _ \| '_ \ / _ \033[01;31m\ \/ /
\033[01;33m| (_) | | | |  __/\033[01;31m>  < 
\033[01;33m \___/|_| |_|\___\033[01;31m/_/\_\

 \033[00m[1] \033[01;32mAll tools \033[00m(\033[01;31m370 tools\033[00m)
 \033[00m[2] \033[01;32mTools category
 \033[00m[3] \033[01;32mUpdate onex
 \033[00m[4] \033[01;32mAbout us
 \033[00m[5] \033[01;32mExit
\007\033[00m[\033[01;34monex\033[00m@\033[01;34mspace\033[00m]$

It seems to work but is not useful if you cant read what it says!

**Comment by rajkumardusad** [comment]
Hey @mawoka-myblock in which terminal you are using onex.

**Comment by mawoka-myblock** [comment]
I am using "konsole" (I think it´s bash) on Arch

**Comment by rajkumardusad** [comment]
May be its not supporting the color code.

**Comment by mawoka-myblock** [comment]
Probably but how do I call the Color code? What is the name of the color code?

**Comment by rajkumardusad** [comment]
I have tested in Ubuntu and other linux terminal it works fine.

**Comment by mawoka-myblock** [comment]
Thats very strange

Am 5. Dezember 2020 20:49:46 MEZ schrieb Rajkumar Dusad <notifications@github.com>:
