### ISSUE TITLE
Onex installing

### ISSUE THREAD

**Issue by Raees231994** [rajkumardusad/onex#26]
Hi Rajkumardusad 
Onex is amazing 
However im struggling with the following
[onex@space]$ 91
Installing ...
Cloning into '/data/data/com.termux/files/home/EasY_HaCk'...
fatal: Unable to read current working directory: No such file or directory
Sorry : 'EasY_HaCk' is not installed !!

**Comment by rajkumardusad** [comment]
Hey @Raees231994 re-open your terminal it will be solved.

**Comment by Raees231994** [comment]
Hey thanks I managed to sort it out

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rajkumardusad** [comment]
Ok
