### ISSUE TITLE
Galaxy s10 plus 

### ISSUE THREAD

**Issue by kiro12kiro** [rajkumardusad/onex#29]
It says installing....
Running setup ..... 
![Screenshot_20201224-045724_Termux](https://user-images.githubusercontent.com/73989177/103056041-8b5ccd00-45a4-11eb-88a2-17094cd809c6.jpg)

**Comment by rajkumardusad** [comment]
Hey @kiro12kiro i have tested in my realme its works fine. re-start your termux and try again, i hope it will works.

**Comment by kiro12kiro** [comment]
It's says the same

**Comment by rajkumardusad** [comment]
Does it throw any error?

**Comment by kiro12kiro** [comment]
I tried and it's did like the photo

**Comment by umeshyadav1008** [comment]
I tried it did not work
