### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by introv3196** [rajkumardusad/onex#30]

**Comment by rajkumardusad** [comment]
Hey @introv3196 you uninstall onex with `onex -r` or `onex remove` command.

**Comment by introv3196** [comment]
$ onex -r
No superuser binary detected.
Are you rooted?
$ onex remove
No superuser binary detected.
Are you rooted?

**Comment by rajkumardusad** [comment]
Hey @introv3196 if you have root access then try with sudo it will works

**Comment by introv3196** [comment]
No , sir I didn't root my phone.

**Comment by rajkumardusad** [comment]
If you have installed sudo in your phone so try with sudo command, may be it will works
