### ISSUE TITLE
Onex not installing!

### ISSUE THREAD

**Issue by Chamindu2005** [rajkumardusad/onex#31]
I am using Termux in android 6.0 and when i try to install onex it show me this error,
"fatal: could not create work tree dir 'onex': No such file or directory"

**Comment by rajkumardusad** [comment]
Hey @Chamindu2005 please read documentation and try again it will works.

**Comment by MR-Bm13** [comment]
How to running tools  after install in onex?

**Comment by spider-8** [comment]
> How to running tools  after install in onex?

Which tool you want to install?
