### ISSUE TITLE
onex is not installed !!

### ISSUE THREAD

**Issue by elimparator12** [rajkumardusad/onex#4]
___  _ __   _____  __
 / _ \| '_ \ / _ \ \/ /
| (_) | | | |  __/>  <
 \___/|_| |_|\___/_/\_\

 Sorry : onex is not installed !!
 Please try again

I have this problem when i use this commend 

chmod +x onex/install

sh onex/install or  ./onex/install

Thanks for help

**Comment by rajkumardusad** [comment]
Hey @elimparator12 may be there are some issue, so in which device or OS you are installing.

**Comment by rohan381** [comment]
Bro can you help me with the zpisher on termux how can I get access to this

**Comment by rajkumardusad** [comment]
Hey @rohan381 this tool is not exists in onex..

**Comment by Mohasinkhan12** [comment]
Plezz[]()_jejej**jsjsjsj**usjs****_
