### ISSUE TITLE
onex 

### ISSUE THREAD

**Issue by PUNJABI19** [rajkumardusad/onex#42]
What is username and password for instahack

**Comment by xrpcryptodad** [comment]
Admin

**Comment by PUNJABI19** [comment]
Ok sir thank you

**Comment by PUNJABI19** [comment]
Thanks sir

**Comment by PUNJABI19** [comment]
> Admin

Please tell briefly

**Comment by PUNJABI19** [comment]
Please tell briefly about username and password for tools

**Comment by xrpcryptodad** [comment]
UN and PW are for SysAdmins If you do not know how to increase admin level ............... welcome to the internet.
