### ISSUE TITLE
Repository Not found

### ISSUE THREAD

**Issue by kawaiineko84** [rajkumardusad/onex#5]
remote: Repository not found.
fatal: repository 'https://github.com/Xi4u7/A-Rat.git/' not found

**Comment by rajkumardusad** [comment]
Hey @kawaiineko84 what is the error??

**Comment by rajkumardusad** [comment]
May be A-Rat tool is deleted by its author.

**Comment by rajkumardusad** [comment]
We will fix it soon...

**Comment by kawaiineko84** [comment]
I see, no prob dude the other package is working well.

**Comment by Christ441** [comment]
@rajkumardusad  @kawaiineko84 How do I run the installed tools...
Plzzz explain me detaily......for SET,WiFi...etc
