### ISSUE TITLE
Don't know how to run tools

### ISSUE THREAD

**Issue by Christ441** [rajkumardusad/onex#6]
What I have to do to run tools 
Can anyone explain detaily......
Plzzzzz

**Comment by rajkumardusad** [comment]
Hey @Christ441 listen, every tools are different so how can you open them with same method ??
Each tool have a different exexution process.

**Comment by Christ441** [comment]
Then how can I know the execution of every tool can you please give me an
idea for this problem......

**Comment by Christ441** [comment]
Or I just want some of the tools excusions. Can you say them

**Comment by rajkumardusad** [comment]
I just want to say that each tool is different for example if you want to run onex so you type `$ onex start` in your terminal. If you want to run tool-x so you have type `$ Tool-X` in your terminal and if you want to run nmap so you will type `$nmap` so you can run all of these tools using one commands you have to use different command for these different tools..

**Comment by rajkumardusad** [comment]
Another simple example :
 If you want to visit America so you will take a flight for america and if you want to visit china so you have to take flight for china and so on...
That means you never visit all of these place by single flight, you have to take a different flights for different countries..

**Comment by rajkumardusad** [comment]
So please tell us the name of the tool that you want to run, we will help or you can google will help. But if you want to find a single way to run all tools so I'm sorry for that no one can help you..

**Comment by Christ441** [comment]
Yah i understand okk 
Social engineer toolkit
WiFi  hacker
I want these two run commands...

**Comment by rajkumardusad** [comment]
Hey @Christ441 don't worry everything is simple and easy..
To run SET use following command
`$ onex install social-engineer-toolkit`
or you can install it for direct by git clone <github link of SET>
`$ cd social-engineer-toolkit`
`$ pip3 install -r requirements.txt`
`$ python setup.py`

i hope, It will works for you.

**Comment by rajkumardusad** [comment]
For wifi-hacker type following command : 
`$ onex install wifi-hacker`
`$ cd wifi-hacker`
`$ chmod +x wifi-hacker.sh`
`$ ./wifi-hacker.sh`
I hope it works for you, if you need any more help so please inform us we are happy to help you...

**Comment by Christ441** [comment]
For SET it's getting error

**Comment by juba224** [comment]
Ill install social fish
How to run this tool?

**Comment by rajkumardusad** [comment]
Hey @juba224 use following commands
Setup SocialFish
`$ cd SocialFish`
`$ python3 -m pip install -r requirements.txt`
Now run SocialFish
`$ python3 SocialFish.py youruser yourpassword`
that's it.

**Comment by sxxTXN** [comment]
I dont know how to use the wifi-hacker tool please help if u can 🙏🏻

**Comment by rajkumardusad** [comment]
For wifi-hacker type following command : 
`$ onex install wifi-hacker`
`$ cd wifi-hacker`
`$ chmod +x wifi-hacker.sh`
`$ ./wifi-hacker.sh`
I hope it works for you, if you need any more help so please inform us we are happy to help you...

**Comment by sxxTXN** [comment]
I did but i dont know what to do before that *-*

**Comment by rajkumardusad** [comment]
Hey @sxxTXN what does this mean?? do that you want to do..

**Comment by sxxTXN** [comment]
![Screenshot_2020-04-15-15-53-51-62](https://user-images.githubusercontent.com/63652159/79239231-9c2f3d80-7e70-11ea-90c9-54829c64b9d7.png)

**Comment by rajkumardusad** [comment]
Hey @sxxTXN it is display a error that means you have not rooted your device so you can not use this tool..

**Comment by sxxTXN** [comment]
Oh thank you 🙏🏻 I'll try to root it
