### ISSUE TITLE
Showing me offline

### ISSUE THREAD

**Issue by niamt1** [rajkumardusad/onex#7]
![Screenshot_2020-04-18-08-50-57](https://user-images.githubusercontent.com/57526598/79626436-01757e00-8152-11ea-8f4f-77d6b5223d2e.png)
Showing that i am offline

**Comment by rajkumardusad** [comment]
Try this : 
$ apt install wget
Now try to install any tool it will works...

**Comment by niamt1** [comment]
thanks

**Comment by niamt1** [comment]
> Try this :
> $ apt install wget
> Now try to install any tool it will works...
Awesome tool
