### ISSUE TITLE
Can we collaborate

### ISSUE THREAD

**Issue by morpheuslord** [rajkumardusad/onex#74]
hello,

i didnt find a way to contact you so i am contacting you via the issues sorry for that.
i wanted to ask if we could collaborate i am working on a new update for my already existing tool [Brute-Framework](https://github.com/morpheuslord/Brute-Hacking-Framework-SourceCode) you can check it out if you want and wanted to ask if you could make a tool installer similar to toolx for that as this is a really great tool and it will be a great addition.
you can further contact me via my email:- morpheuslord@protonmail.com

hoping for a positive answer
thank you
morpheuslord

**Comment by rajkumardusad** [comment]
Hey @morpheuslord thanks for contacting us. Did you want that we will add this in toolx and onex?

**Comment by morpheuslord** [comment]
onex or toolx any of them which have the best i just want your help to design a tool installer for my own tool

**Comment by morpheuslord** [comment]
> Hey @morpheuslord thanks for contacting us. Did you want that we will add this in toolx and onex?

onex or toolx any of them which have the best i just want your help to design a tool installer for my own tool

**Comment by rajkumardusad** [comment]
Yes sure we do that, but im available only on weekends.

**Comment by morpheuslord** [comment]
Yes thank you for your help 👍

**Comment by morpheuslord** [comment]
Can you recreate the script in batch and clearly ask the dowload location for where it should install it for windows

**Comment by rajkumardusad** [comment]
Hey @morpheuslord i didn't use windows and i don't have windows system so sorry for that i can't create batch script.

**Comment by morpheuslord** [comment]
Ok
