### ISSUE TITLE
Bro I do ur Steps but I don’t knew what I do next of this

### ISSUE THREAD

**Issue by 0797578336** [rajkumardusad/onex#76]
![image](https://user-images.githubusercontent.com/90515330/132952598-ece75ad8-de96-4d60-a022-2ff338f31249.png)

**Comment by rajkumardusad** [comment]
Just type onex in your terminal it will show help.

**Comment by 0797578336** [comment]
Thx bro for message 

Bro next what I do

![image](https://user-images.githubusercontent.com/90515330/132955570-a13de719-83fd-4ed2-bf16-3718173d49d6.png)

**Comment by 0797578336** [comment]
Please message bro I waiting￼ thx
