### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Abdulwajid408** [rajkumardusad/onex#9]
Bro whenever I want to install any tools it always show the message . "You are offline". I tried Tool-X only in Termux
![Screenshot_2020-05-03-06-46-54-702_com termux](https://user-images.githubusercontent.com/56129464/80896261-411f9680-8d0a-11ea-8fef-c11a7dd993b4.jpg)

**Comment by rajkumardusad** [comment]
Hey @Abdulwajid408 yes there is a small issue.
Try this command and try again.
`$ pkg install wget`
Not it will works.
